### ISSUE TITLE
Ambigous reference

### ISSUE THREAD

**Issue by Goule** [apegroup/APESuperHUD#11]
Hi, 

When I'm trying to display message, I got this : 
<img width="864" alt="capture d ecran 2016-09-16 a 11 39 43" src="https://cloud.githubusercontent.com/assets/21126201/18581788/6a492854-7c02-11e6-8424-e9c50d8c2533.png">

With 0.6 version and cocoapod. Have you any solution ? 

Thank you !

**Comment by eFagerman** [comment]
Hi,
Is sourceController a UIView or a view controller? The presenting view needs to be a UIView.
There are new versions you can try:  1.0 (Swift 3.0), and 0.6.2 (Swift 2.2)

**Comment by Goule** [comment]
Oh yes, my presentingView was UIViewController.. Thank you man !
