### ISSUE TITLE
iOS 10 backgroundBlurEffect issue

### ISSUE THREAD

**Issue by floriangbh** [apegroup/APESuperHUD#12]
Hello,

Since iOS 10 update, I found issue with backgroundBlurEffect property. The background seem to appear blurred / un blurred / blurred when the loader appear.

To reproduce this issue, just replace in the demo project 
`APESuperHUD.appearance.backgroundBlurEffect = .none
`
by : 
`APESuperHUD.appearance.backgroundBlurEffect = .dark`

Have you any solution for this issue ? :) 

Thank you

**Comment by Goule** [comment]
Same issue. Any chance to fix it ?

**Comment by floriangbh** [comment]
Seem to be fixed with the last release.

Thank's for your feedback... or not !
