### ISSUE TITLE
Addition

### ISSUE THREAD

**Issue by mixo44** [apegroup/APESuperHUD#16]
Hello. Thank you for the framework. It works good.
Please, can you add a functions which shows weather the `HudView` is visible on the given view or not.
Like this:
```
public static func isVisible(in view: UIView) -> Bool {
        
        var status = false
        if getHudView(presentingView: view) != nil {
            
            status = true
        }
        
        return status
}
```

Thanks!

**Comment by mixo44** [comment]
I also have created a pull request.

**Comment by edvaldeysteinsson** [comment]
@erifa could you look in to this, the PR was merged in to develop but it hasn't made it's way to master

Look here -> [https://github.com/apegroup/APESuperHUD/pull/17](https://github.com/apegroup/APESuperHUD/pull/17)

**Comment by edvaldeysteinsson** [comment]
Closing this, it will be available in the next release
